version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  pgdata:
